import React from 'react';
import { View, Text, FlatList, Image, Button, StyleSheet } from 'react-native';

const App = () => {
  const products = [
    { id: '1', name: 'Lotus Silk Dress', price: '1200 USD' },
    { id: '2', name: 'Bogolan Jacket', price: '900 USD' },
  ];

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Welcome to COULEURNOIR Boutique</Text>
      <FlatList
        data={products}
        renderItem={({ item }) => (
          <View style={styles.productCard}>
            <Text>{item.name}</Text>
            <Text>{item.price}</Text>
            <Button title="Buy Now" onPress={() => alert('Proceed to Payment')} />
          </View>
        )}
        keyExtractor={(item) => item.id}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, padding: 20 },
  title: { fontSize: 24, fontWeight: 'bold', marginBottom: 20 },
  productCard: { marginBottom: 20, padding: 10, borderWidth: 1, borderRadius: 8 },
});

export default App;
